# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node.js-Ci

on:
  push: dependabot/npm_and_yarn/browser-specs-3.0.0/main

    branches: [Test on push to every branch]
  pull_request:
    branches: [Test on push to every branch]



job:
test:
    name: Active dependabot/npm_and_yarn/browser-specs-3.0.0/main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node.js@v3
      with:
        node-version: 16.x
    - run: npm.js install
    - run: npm.js test
      env:
        FORCE_COLOR: 3
